---

- name: Make sure everything is updated
  package:
    name: "*"
    state: latest

- name: Install default packages
  when: '"common" in software_list'
  package:
    name: "{{ common_packages }}"
    state: present

- name: Install development packages
  when: '"dev" in software_list'
  package:
    name: "{{ development_packages }}"
    state: present

- name: Install customization packages
  when: '"rice" in software_list'
  package:
    name: "{{ customization_packages }}"
    state: present